# Generated by Django 4.0.8 on 2024-07-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tblclasses',
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cin_eleve', models.CharField(max_length=20, unique=True)),
                ('sexe', models.CharField(choices=[('masculin', 'Masculin'), ('feminin', 'Feminin')], max_length=10)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('photo_profil', models.ImageField(upload_to='photos')),
                ('date_admission', models.DateField()),
                ('niveau_scolaire', models.CharField(max_length=50)),
                ('nom_parent', models.CharField(max_length=100)),
                ('prenom_parent', models.CharField(max_length=100)),
                ('date_naissance_parent', models.DateField()),
                ('lieu_naissance_parent', models.CharField(max_length=100)),
                ('tel_parent', models.CharField(max_length=20)),
                ('user_username', models.CharField(blank=True, max_length=150, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_password', models.CharField(blank=True, max_length=150, null=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.classe')),
            ],
            options={
                'db_table': 'tblstudents',
            },
        ),
        migrations.CreateModel(
            name='AbscenceEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2000-02-02')),
                ('type', models.CharField(choices=[('Justifier', 'Justifier'), ('Non-justifier', 'Non-justifier')], default='Non-justifier', max_length=20)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abscences', to='students.eleve')),
            ],
            options={
                'db_table': 'tblabsenceseleves',
                'ordering': ['date'],
            },
        ),
    ]
