# Generated by Django 4.0.8 on 2024-07-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_matiere_note_controle'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle',
            name='type',
            field=models.CharField(choices=[('Devoir', 'Devoir'), ('Examen', 'Examen')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
