# Generated by Django 5.0.2 on 2024-08-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_annescolaire_remove_eleve_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='user_password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='user_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
