# Generated by Django 5.0.2 on 2024-07-22 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_controle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='controle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.controle'),
        ),
    ]
