# Generated by Django 5.0.2 on 2024-07-27 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_note_controle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('masculin', 'Masculin'), ('feminin', 'Feminin')], max_length=10)),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tel', models.CharField(max_length=15)),
                ('photo_profil', models.ImageField(upload_to='photos')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professeurs', to='students.classe')),
            ],
        ),
    ]
