# Generated by Django 5.0.2 on 2024-07-27 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_professeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbscenceProfesseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2000-02-02')),
                ('type', models.CharField(choices=[('Justifier', 'Justifier'), ('Non-justifier', 'Non-justifier')], default='Non-justifier', max_length=20)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abscences', to='students.professeur')),
            ],
            options={
                'db_table': 'tblabsencesprofesseurs',
                'ordering': ['date'],
            },
        ),
    ]
