# Generated by Django 5.0.2 on 2024-07-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_abscenceprofesseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='user_password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='user_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
