# Generated by Django 5.0.2 on 2024-07-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_professeur_user_email_professeur_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='email',
        ),
    ]
