# Generated by Django 4.0.1 on 2024-06-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='sexe',
            field=models.CharField(choices=[('masculin', 'Masculin'), ('feminin', 'Feminin')], max_length=10),
        ),
    ]
