# Generated by Django 4.0.1 on 2024-06-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_professeur_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='niveau_enseignement',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
