# Generated by Django 4.0.1 on 2024-06-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_professeur_niveau_enseignement'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='photo_profil',
            field=models.ImageField(default='', upload_to='photos'),
            preserve_default=False,
        ),
    ]
